version: '3.8'

services:
  astana-client:
    build:
      context: .
      dockerfile: astana_client/Dockerfile
    ports:
      - "81:80"

  astana-server:
    build:
      context: .
      dockerfile: astana_server/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development


  saudi-client:
    build:
      context: .
      dockerfile: astana_client/Dockerfile
    ports:
      - "82:80"

  saudi-server:
    build:
      context: .
      dockerfile: astana_server/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - NODE_ENV=development

  abu-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "83:80"

  abu-server:
    build:
      context: .
      dockerfile: abu_server/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"