version: '3.8'

services:
  astana-client:
    build:
      context: .
      dockerfile: astana_client/Dockerfile
    ports:
      - "81:81"
    networks:
      - drones

  astana-server:
    build:
      context: .
      dockerfile: astana_server/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    networks:
      - drones


  saudi-client:
    build:
      context: .
      dockerfile: astana_client/Dockerfile
    ports:
      - "82:82"
    networks:
      - drones

  saudi-server:
    build:
      context: .
      dockerfile: saudi_server/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
    networks:
      - drones

  abu-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "83:83"
    networks:
      - drones

  abu-server:
    build:
      context: .
      dockerfile: abu_server/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
    networks:
      - drones

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - abu-client
      - abu-server
      - astana-client
      - astana-server
      - saudi-client
      - saudi-server
    networks:
      - drones



networks:
  drones:
    driver: bridge